package provider

import (
	"context"
	"fmt"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &DeliveryTimeResource{}
	_ resource.ResourceWithConfigure   = &DeliveryTimeResource{}
	_ resource.ResourceWithImportState = &DeliveryTimeResource{}
)

func NewDeliveryTimeResource() resource.Resource {
	return &DeliveryTimeResource{}
}

type DeliveryTimeResource struct {
	client *EmporixClient
}

type DeliveryTimeResourceModel struct {
	ID               types.String `tfsdk:"id"`
	Name             types.String `tfsdk:"name"`
	SiteCode         types.String `tfsdk:"site_code"`
	IsDeliveryDay    types.Bool   `tfsdk:"is_delivery_day"`
	ZoneID           types.String `tfsdk:"zone_id"`
	Day              types.Object `tfsdk:"day"`
	IsForAllZones    types.Bool   `tfsdk:"is_for_all_zones"`
	TimeZoneID       types.String `tfsdk:"time_zone_id"`
	DeliveryDayShift types.Int64  `tfsdk:"delivery_day_shift"`
	Slots            types.List   `tfsdk:"slots"`
}

type DeliveryDayModel struct {
	Weekday types.String `tfsdk:"weekday"`
}

type DeliveryTimeSlotModel struct {
	ShippingMethod    types.String `tfsdk:"shipping_method"`
	DeliveryTimeRange types.Object `tfsdk:"delivery_time_range"`
	CutOffTime        types.Object `tfsdk:"cut_off_time"`
	Capacity          types.Int64  `tfsdk:"capacity"`
}

type TimeRangeModel struct {
	TimeFrom types.String `tfsdk:"time_from"`
	TimeTo   types.String `tfsdk:"time_to"`
}

type CutOffTimeModel struct {
	Time              types.String `tfsdk:"time"`
	DeliveryCycleName types.String `tfsdk:"delivery_cycle_name"`
}

func (r *DeliveryTimeResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_delivery_time"
}

func (r *DeliveryTimeResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages delivery time slot configurations for scheduled deliveries.",

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier generated by the API.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "Unique name for the delivery time configuration.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"site_code": schema.StringAttribute{
				MarkdownDescription: "Site code. Typically 'main' for single-shop tenants.",
				Required:            true,
			},
			"is_delivery_day": schema.BoolAttribute{
				MarkdownDescription: "Whether this is an active delivery day.",
				Optional:            true,
				Computed:            true,
				Default:             booldefault.StaticBool(true),
			},
			"zone_id": schema.StringAttribute{
				MarkdownDescription: "Shipping zone ID this delivery time applies to. Required if is_for_all_zones is false.",
				Optional:            true,
			},
			"is_for_all_zones": schema.BoolAttribute{
				MarkdownDescription: "Whether this delivery time applies to all zones.",
				Optional:            true,
				Computed:            true,
				Default:             booldefault.StaticBool(false),
			},
			"time_zone_id": schema.StringAttribute{
				MarkdownDescription: "Timezone identifier (e.g., 'Europe/Warsaw', 'America/New_York').",
				Required:            true,
			},
			"delivery_day_shift": schema.Int64Attribute{
				MarkdownDescription: "Number of days to shift delivery from order date.",
				Optional:            true,
				Computed:            true,
				Default:             int64default.StaticInt64(0),
			},
			"day": schema.SingleNestedAttribute{
				MarkdownDescription: "Day configuration for this delivery time.",
				Optional:            true,
				Attributes: map[string]schema.Attribute{
					"weekday": schema.StringAttribute{
						MarkdownDescription: "Day of the week (MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY).",
						Required:            true,
						Validators: []validator.String{
							stringvalidator.OneOf("MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"),
						},
					},
				},
			},
			"slots": schema.ListNestedAttribute{
				MarkdownDescription: "Delivery time slots with shipping methods and capacity.",
				Optional:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"shipping_method": schema.StringAttribute{
							MarkdownDescription: "Shipping method identifier.",
							Required:            true,
						},
						"capacity": schema.Int64Attribute{
							MarkdownDescription: "Maximum number of deliveries for this slot.",
							Required:            true,
						},
						"delivery_time_range": schema.SingleNestedAttribute{
							MarkdownDescription: "Time range for delivery.",
							Required:            true,
							Attributes: map[string]schema.Attribute{
								"time_from": schema.StringAttribute{
									MarkdownDescription: "Start time in HH:MM:SS format (e.g., '10:00:00').",
									Required:            true,
									Validators: []validator.String{
										stringvalidator.RegexMatches(
											regexp.MustCompile(`^([0-1][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])$`),
											"must be in HH:MM:SS format (e.g., '10:00:00')",
										),
									},
								},
								"time_to": schema.StringAttribute{
									MarkdownDescription: "End time in HH:MM:SS format (e.g., '12:00:00').",
									Required:            true,
									Validators: []validator.String{
										stringvalidator.RegexMatches(
											regexp.MustCompile(`^([0-1][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])$`),
											"must be in HH:MM:SS format (e.g., '12:00:00')",
										),
									},
								},
							},
						},
						"cut_off_time": schema.SingleNestedAttribute{
							MarkdownDescription: "Order cutoff time for this slot.",
							Optional:            true,
							Attributes: map[string]schema.Attribute{
								"time": schema.StringAttribute{
									MarkdownDescription: "Cutoff timestamp in ISO 8601 format (e.g., '2023-06-12T18:00:00.000Z').",
									Required:            true,
								},
								"delivery_cycle_name": schema.StringAttribute{
									MarkdownDescription: "Delivery cycle identifier (e.g., 'morning', 'afternoon').",
									Required:            true,
								},
							},
						},
					},
				},
			},
		},
	}
}

func (r *DeliveryTimeResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*EmporixClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *EmporixClient, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *DeliveryTimeResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data DeliveryTimeResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Creating delivery time", map[string]interface{}{
		"name":      data.Name.ValueString(),
		"site_code": data.SiteCode.ValueString(),
	})

	// Build API request
	deliveryTime := &DeliveryTime{
		SiteCode:         data.SiteCode.ValueString(),
		Name:             data.Name.ValueString(),
		IsDeliveryDay:    data.IsDeliveryDay.ValueBool(),
		IsForAllZones:    data.IsForAllZones.ValueBool(),
		TimeZoneID:       data.TimeZoneID.ValueString(),
		DeliveryDayShift: int(data.DeliveryDayShift.ValueInt64()),
	}

	// Set zone_id if provided
	if !data.ZoneID.IsNull() {
		deliveryTime.ZoneID = data.ZoneID.ValueString()
	}

	// Parse day if provided
	if !data.Day.IsNull() {
		var dayModel DeliveryDayModel
		resp.Diagnostics.Append(data.Day.As(ctx, &dayModel, basetypes.ObjectAsOptions{})...)
		if resp.Diagnostics.HasError() {
			return
		}
		deliveryTime.Day = &DeliveryDay{
			Weekday: dayModel.Weekday.ValueString(),
		}
	}

	// Parse slots if provided
	if !data.Slots.IsNull() {
		var slotsModels []DeliveryTimeSlotModel
		resp.Diagnostics.Append(data.Slots.ElementsAs(ctx, &slotsModels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}

		for _, slotModel := range slotsModels {
			slot := DeliveryTimeSlot{
				ShippingMethod: slotModel.ShippingMethod.ValueString(),
				Capacity:       int(slotModel.Capacity.ValueInt64()),
			}

			// Parse delivery time range
			var timeRangeModel TimeRangeModel
			resp.Diagnostics.Append(slotModel.DeliveryTimeRange.As(ctx, &timeRangeModel, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			slot.DeliveryTimeRange = &TimeRange{
				TimeFrom: timeRangeModel.TimeFrom.ValueString(),
				TimeTo:   timeRangeModel.TimeTo.ValueString(),
			}

			// Parse cut off time if provided
			if !slotModel.CutOffTime.IsNull() {
				var cutOffTimeModel CutOffTimeModel
				resp.Diagnostics.Append(slotModel.CutOffTime.As(ctx, &cutOffTimeModel, basetypes.ObjectAsOptions{})...)
				if resp.Diagnostics.HasError() {
					return
				}
				slot.CutOffTime = &CutOffTime{
					Time:              cutOffTimeModel.Time.ValueString(),
					DeliveryCycleName: cutOffTimeModel.DeliveryCycleName.ValueString(),
				}
			}

			deliveryTime.Slots = append(deliveryTime.Slots, slot)
		}
	}

	// Create via API
	createdDeliveryTime, err := r.client.CreateDeliveryTime(ctx, deliveryTime)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create delivery time, got error: %s", err))
		return
	}

	// If create response is empty, read back to get the ID
	if createdDeliveryTime == nil {
		tflog.Debug(ctx, "Create response was empty, reading back to get ID")
		// Try to get by name first to find the ID
		actualDeliveryTime, err := r.client.GetDeliveryTime(ctx, data.Name.ValueString())
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read created delivery time, got error: %s", err))
			return
		}
		createdDeliveryTime = actualDeliveryTime
	}

	// Store the generated ID
	if createdDeliveryTime.ID != "" {
		data.ID = types.StringValue(createdDeliveryTime.ID)
	} else {
		resp.Diagnostics.AddError("API Error", "API did not return an ID for the created delivery time")
		return
	}

	// Read back using the ID to get actual state
	tflog.Debug(ctx, "Reading back created delivery time using ID", map[string]interface{}{
		"id": data.ID.ValueString(),
	})
	actualDeliveryTime, err := r.client.GetDeliveryTime(ctx, data.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read created delivery time, got error: %s", err))
		return
	}

	// Create fresh state model from API response (don't reuse plan data)
	var stateModel DeliveryTimeResourceModel
	r.syncModelFromAPI(ctx, &stateModel, actualDeliveryTime, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &stateModel)...)
}

func (r *DeliveryTimeResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data DeliveryTimeResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Reading delivery time", map[string]interface{}{
		"id":   data.ID.ValueString(),
		"name": data.Name.ValueString(),
	})

	actualDeliveryTime, err := r.client.GetDeliveryTime(ctx, data.ID.ValueString())
	if err != nil {
		if IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read delivery time, got error: %s", err))
		return
	}

	// Create fresh state model from API response
	var stateModel DeliveryTimeResourceModel
	r.syncModelFromAPI(ctx, &stateModel, actualDeliveryTime, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &stateModel)...)
}

func (r *DeliveryTimeResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data DeliveryTimeResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Updating delivery time", map[string]interface{}{
		"id":   data.ID.ValueString(),
		"name": data.Name.ValueString(),
	})

	// Build API request (same as Create)
	deliveryTime := &DeliveryTime{
		SiteCode:         data.SiteCode.ValueString(),
		Name:             data.Name.ValueString(),
		IsDeliveryDay:    data.IsDeliveryDay.ValueBool(),
		IsForAllZones:    data.IsForAllZones.ValueBool(),
		TimeZoneID:       data.TimeZoneID.ValueString(),
		DeliveryDayShift: int(data.DeliveryDayShift.ValueInt64()),
	}

	if !data.ZoneID.IsNull() {
		deliveryTime.ZoneID = data.ZoneID.ValueString()
	}

	if !data.Day.IsNull() {
		var dayModel DeliveryDayModel
		resp.Diagnostics.Append(data.Day.As(ctx, &dayModel, basetypes.ObjectAsOptions{})...)
		if resp.Diagnostics.HasError() {
			return
		}
		deliveryTime.Day = &DeliveryDay{
			Weekday: dayModel.Weekday.ValueString(),
		}
	}

	if !data.Slots.IsNull() {
		var slotsModels []DeliveryTimeSlotModel
		resp.Diagnostics.Append(data.Slots.ElementsAs(ctx, &slotsModels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}

		for _, slotModel := range slotsModels {
			slot := DeliveryTimeSlot{
				ShippingMethod: slotModel.ShippingMethod.ValueString(),
				Capacity:       int(slotModel.Capacity.ValueInt64()),
			}

			var timeRangeModel TimeRangeModel
			resp.Diagnostics.Append(slotModel.DeliveryTimeRange.As(ctx, &timeRangeModel, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			slot.DeliveryTimeRange = &TimeRange{
				TimeFrom: timeRangeModel.TimeFrom.ValueString(),
				TimeTo:   timeRangeModel.TimeTo.ValueString(),
			}

			if !slotModel.CutOffTime.IsNull() {
				var cutOffTimeModel CutOffTimeModel
				resp.Diagnostics.Append(slotModel.CutOffTime.As(ctx, &cutOffTimeModel, basetypes.ObjectAsOptions{})...)
				if resp.Diagnostics.HasError() {
					return
				}
				slot.CutOffTime = &CutOffTime{
					Time:              cutOffTimeModel.Time.ValueString(),
					DeliveryCycleName: cutOffTimeModel.DeliveryCycleName.ValueString(),
				}
			}

			deliveryTime.Slots = append(deliveryTime.Slots, slot)
		}
	}

	// Update via API
	_, err := r.client.UpdateDeliveryTime(ctx, data.ID.ValueString(), deliveryTime)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update delivery time, got error: %s", err))
		return
	}

	// Read back using ID
	tflog.Debug(ctx, "Reading back updated delivery time using ID", map[string]interface{}{
		"id": data.ID.ValueString(),
	})
	actualDeliveryTime, err := r.client.GetDeliveryTime(ctx, data.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read updated delivery time, got error: %s", err))
		return
	}

	// Create fresh state model from API response (don't reuse plan data)
	var stateModel DeliveryTimeResourceModel
	r.syncModelFromAPI(ctx, &stateModel, actualDeliveryTime, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &stateModel)...)
}

func (r *DeliveryTimeResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data DeliveryTimeResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Deleting delivery time", map[string]interface{}{
		"id":   data.ID.ValueString(),
		"name": data.Name.ValueString(),
	})

	err := r.client.DeleteDeliveryTime(ctx, data.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete delivery time, got error: %s", err))
		return
	}

	tflog.Debug(ctx, "Successfully deleted delivery time")
}

func (r *DeliveryTimeResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import ID format: "id"
	// Example: terraform import emporix_delivery_time.example abc123
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

// syncModelFromAPI syncs the Terraform model from API response
func (r *DeliveryTimeResource) syncModelFromAPI(ctx context.Context, model *DeliveryTimeResourceModel, api *DeliveryTime, diags *diag.Diagnostics) {
	model.ID = types.StringValue(api.ID)
	model.Name = types.StringValue(api.Name)
	model.SiteCode = types.StringValue(api.SiteCode)
	model.IsDeliveryDay = types.BoolValue(api.IsDeliveryDay)
	model.IsForAllZones = types.BoolValue(api.IsForAllZones)
	model.TimeZoneID = types.StringValue(api.TimeZoneID)
	model.DeliveryDayShift = types.Int64Value(int64(api.DeliveryDayShift))

	if api.ZoneID != "" {
		model.ZoneID = types.StringValue(api.ZoneID)
	} else {
		model.ZoneID = types.StringNull()
	}

	// Sync day
	if api.Day != nil {
		dayModel := DeliveryDayModel{
			Weekday: types.StringValue(api.Day.Weekday),
		}
		dayObj, d := types.ObjectValueFrom(ctx, map[string]attr.Type{
			"weekday": types.StringType,
		}, dayModel)
		diags.Append(d...)
		model.Day = dayObj
	} else {
		model.Day = types.ObjectNull(map[string]attr.Type{
			"weekday": types.StringType,
		})
	}

	// Sync slots
	if len(api.Slots) > 0 {
		var slotsModels []DeliveryTimeSlotModel
		for _, slot := range api.Slots {
			slotModel := DeliveryTimeSlotModel{
				ShippingMethod: types.StringValue(slot.ShippingMethod),
				Capacity:       types.Int64Value(int64(slot.Capacity)),
			}

			// Time range
			if slot.DeliveryTimeRange != nil {
				timeRangeModel := TimeRangeModel{
					TimeFrom: types.StringValue(slot.DeliveryTimeRange.TimeFrom),
					TimeTo:   types.StringValue(slot.DeliveryTimeRange.TimeTo),
				}
				timeRangeObj, d := types.ObjectValueFrom(ctx, map[string]attr.Type{
					"time_from": types.StringType,
					"time_to":   types.StringType,
				}, timeRangeModel)
				diags.Append(d...)
				slotModel.DeliveryTimeRange = timeRangeObj
			}

			// Cut off time
			if slot.CutOffTime != nil {
				cutOffTimeModel := CutOffTimeModel{
					Time:              types.StringValue(slot.CutOffTime.Time),
					DeliveryCycleName: types.StringValue(slot.CutOffTime.DeliveryCycleName),
				}
				cutOffTimeObj, d := types.ObjectValueFrom(ctx, map[string]attr.Type{
					"time":                types.StringType,
					"delivery_cycle_name": types.StringType,
				}, cutOffTimeModel)
				diags.Append(d...)
				slotModel.CutOffTime = cutOffTimeObj
			} else {
				slotModel.CutOffTime = types.ObjectNull(map[string]attr.Type{
					"time":                types.StringType,
					"delivery_cycle_name": types.StringType,
				})
			}

			slotsModels = append(slotsModels, slotModel)
		}

		slotsList, d := types.ListValueFrom(ctx, types.ObjectType{
			AttrTypes: map[string]attr.Type{
				"shipping_method": types.StringType,
				"capacity":        types.Int64Type,
				"delivery_time_range": types.ObjectType{
					AttrTypes: map[string]attr.Type{
						"time_from": types.StringType,
						"time_to":   types.StringType,
					},
				},
				"cut_off_time": types.ObjectType{
					AttrTypes: map[string]attr.Type{
						"time":                types.StringType,
						"delivery_cycle_name": types.StringType,
					},
				},
			},
		}, slotsModels)
		diags.Append(d...)
		model.Slots = slotsList
	} else {
		model.Slots = types.ListNull(types.ObjectType{
			AttrTypes: map[string]attr.Type{
				"shipping_method": types.StringType,
				"capacity":        types.Int64Type,
				"delivery_time_range": types.ObjectType{
					AttrTypes: map[string]attr.Type{
						"time_from": types.StringType,
						"time_to":   types.StringType,
					},
				},
				"cut_off_time": types.ObjectType{
					AttrTypes: map[string]attr.Type{
						"time":                types.StringType,
						"delivery_cycle_name": types.StringType,
					},
				},
			},
		})
	}
}
